#!/bin/bash
clear
echo "This script will automaticly delete itself after installation."
echo "Are you sure you want to install the krushed zsh configs? (ENTER/Ctrl + c)"
read
clear
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k

cp -r -f ~/.krushed-zshrc ~/.zshrc

echo "ZSH IS INSTALLED"
sudo rm -rf /usr/bin/install-krushed-zsh