[package]
name = "krushed-arch-installer"
version = "0.1.0"
edition = "2021"

[dependencies]
cpuid = "0.1.1"
crossterm = "0.28.1"
dialoguer = "0.11.0"
indicatif = "0.17.8"
mpsc = "0.2.3"
nix = "0.23.0"
ratatui = "0.28.1"
